<?php
namespace duels\utils;

class BinarySeralize 
{

    public static function _IntToSimbolString(int $num = 0): string
    {
        $simbol = [' ','§c❶','§e❷','§6❸','§a❹','§a❺',' '];
        if(isset($simbol[$num]) && $num <= 5)  
        {
            return $simbol[$num];
        }
        return $simbol[0];
    }

    public static function _IntToSimbolStringHealth(int $health, int $max): string
    {
        $key = '';
        if($max === 20)
        {
            if($health === 20){$key = '§4❤❤❤❤❤❤❤❤❤❤';}
            if($health === 18 || $health === 19){$key = '§4❤❤❤❤❤❤❤❤❤§8❤';}
            if($health === 16 || $health === 17){$key = '§4❤❤❤❤❤❤❤❤§8❤❤';}
            if($health === 14 || $health === 15){$key = '§4❤❤❤❤❤❤❤§8❤❤❤';}
            if($health === 12 || $health === 13){$key = '§4❤❤❤❤❤❤§8❤❤❤❤';}
            if($health === 10 || $health === 11){$key = '§4❤❤❤❤❤§8❤❤❤❤❤';}
            if($health === 8 || $health === 9){$key = '§4❤❤❤❤§8❤❤❤❤❤❤';}
            if($health === 6 || $health === 7){$key = '§4❤❤❤§8❤❤❤❤❤❤❤';}
            if($health === 4 || $health === 5){$key = '§4❤❤§8❤❤❤❤❤❤❤❤';}
            if($health === 2 || $health === 3){$key = '§4❤§8❤❤❤❤❤❤❤❤❤';}
            return $key."\n";
        }
        if($max === 40)
        {
            if($health === 40){
                $line1 = '§4❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 38 || $health === 39){
                $line1 = '§4❤❤❤❤❤❤❤❤❤§8❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 36 || $health === 37){
                $line1 = '§4❤❤❤❤❤❤❤❤§8❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 34 || $health === 35){
                $line1 = '§4❤❤❤❤❤❤❤§8❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 32 || $health === 33){
                $line1 = '§4❤❤❤❤❤❤§8❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 30 || $health === 31){
                $line1 = '§4❤❤❤❤❤§8❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 28 || $health === 29){
                $line1 = '§4❤❤❤❤§8❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 26 || $health === 27){
                $line1 = '§4❤❤❤§8❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 24 || $health === 25){
                $line1 = '§4❤❤§8❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 22 || $health === 23){
                $line1 = '§4❤§8❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            } 
            if($health === 20 || $health === 21){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 18 || $health === 19){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤❤§8❤';
                $key = $line1."\n".$line2;
            }
            if($health === 16 || $health === 17){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤❤§8❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 14 || $health === 15){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤❤§8❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 12 || $health === 13){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤❤§8❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 10  || $health === 11){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤❤§8❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 8  || $health === 9){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤❤§8❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 6 || $health === 7){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤❤§8❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 4 || $health === 5){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤❤§8❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            }
            if($health === 2 || $health === 3){
                $line1 = '§8❤❤❤❤❤❤❤❤❤❤';
                $line2 = '§4❤§8❤❤❤❤❤❤❤❤❤';
                $key = $line1."\n".$line2;
            } 
            return $key."\n§e";   
    }
}

    public static function _encodeTerminalString(string $message): string{
    $message = str_replace('§f',"\x1b[38;5;231m",$message);
    $message = str_replace("§e","\x1b[38;5;227m",$message);
    $message = str_replace('§d',"\x1b[38;5;207m",$message);
    $message = str_replace("§c","\x1b[38;5;203m",$message);
    $message = str_replace("§b","\x1b[38;5;87m",$message);
    $message = str_replace("§a","\x1b[38;5;83m",$message);
    $message = str_replace("§9","\x1b[38;5;63m",$message);
    $message = str_replace('§8',"\x1b[38;5;59m",$message);
    $message = str_replace("§7","\x1b[38;5;145m",$message);
    $message = str_replace("§6","\x1b[38;5;214m",$message);
    $message = str_replace("§5","\x1b[38;5;127m",$message);
    $message = str_replace("§4","\x1b[38;5;124m",$message);
    $message = str_replace("§3","\x1b[38;5;37m",$message);
    $message = str_replace("§2","\x1b[38;5;34m",$message);
    $message = str_replace("§1","\x1b[38;5;19m",$message);
    $message = str_replace("§0","\x1b[38;5;16m",$message);
    $message = str_replace("§r","\x1b[m",$message);
    $message = str_replace("§l","\x1b[1m",$message);
    $message = str_replace("§o","\x1b[3m",$message);
    $message = str_replace("§n","\x1b[4m",$message);
    $message = str_replace("§m","\x1b[9m",$message);
    $message = str_replace("§k","",$message);
    return $message;
    }


    public static function _getSkinToByte(): string
    {
        return base64_decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTKQ/+TicO/kolDf4wGAj+PR8L/j0fC/5TKQ/+ORwJ/v3cuv7+8uf+/vLn/v7t3f793Lr+/vDi/v7y5/7+7Nj+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIhDP41Ggn+ORwJ/jAYCP45HAn+UykP/jUaCf45HAn+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPR8L/jkcCf5KJQ3+RiMN/k4nDv4wGAj+RiMN/lMpD/794cT+/uzY/v7o0/7+8OL+/vDi/v7o0/793r/+/dy6/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOJw7+PR8L/k4nDv5OJw7+NRoJ/jUaCf4sFgf+UykP/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkcCf41Ggn+UykP/j0fC/49Hwv+NRoJ/lMpD/5CIQz+/eHE/v3ev/7+5s7+/uPJ/v3cuv794cT+/vLn/v7o0/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPR8L/jkcCf5GIw3+LBYH/jAYCP4wGAj+LBYH/kIhDP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9Hwv+NRoJ/jAYCP5XLBD+PR8L/jAYCP49Hwv+VywQ/v3cuv7+48n+/uPJ/v3cuv794cT+/uPJ/v3hxP793Lr+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwWB/49Hwv+NRoJ/kIhDP5GIw3+ORwJ/kIhDP4sFgf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVywQ/kIhDP5TKQ/+VywQ/lMpD/4wGAj+QiEM/k4nDv7+7d3+/vLn/v3cuv7+6NP+/dy6/v3ev/7+6NP+/ubO/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXLBD+ORwJ/jAYCP5GIw3+PR8L/kolDf5XLBD+UykP/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD0fC/5CIQz+VywQ/lcsEP41Ggn+ORwJ/jkcCf41Ggn+/d6//v7o0/794cT+/uPJ/v7w4v7+5s7+/u3d/v7y5/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVywQ/jkcCf5CIQz+VywQ/kIhDP5GIw3+ORwJ/jkcCf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCIQz+PR8L/kYjDf5KJQ3+ORwJ/jUaCf4wGAj+QiEM/v7t3f7+48n+/ujT/v7w4v794cT+/u3d/v3ev/794cT+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4nDv5TKQ/+QiEM/jAYCP5OJw7+TicO/kIhDP4wGAj+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAORwJ/lcsEP49Hwv+TicO/lMpD/49Hwv+VywQ/lcsEP7+6NP+/d6//v7s2P7+8OL+/uzY/v3cuv7+6NP+/u3d/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1Ggn+LBYH/j0fC/5TKQ/+LBYH/iwWB/5KJQ3+VywQ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGIw3+PR8L/kYjDf5XLBD+SiUN/kolDf5TKQ/+VywQ/j0fC/41Ggn+NRoJ/iwWB/41Ggn+ORwJ/lMpD/5XLBD+TicO/jAYCP45HAn+MBgI/jkcCf5GIw3+TicO/iwWB/5OJw7+TicO/jAYCP5OJw7+NRoJ/kolDf4sFgf+VywQ/kolDf41Ggn+UykP/jAYCP41Ggn+TicO/k4nDv45HAn+LBYH/jkcCf5OJw7+TicO/j0fC/5TKQ/+LBYH/k4nDv5XLBD+NRoJ/kYjDf5KJQ3+VywQ/lcsEP4wGAj+TicO/kYjDf45HAn+MBgI/jAYCP5OJw7+RiMN/kIhDP5TKQ/+SiUN/jAYCP5CIQz+ORwJ/jAYCP5XLBD+SiUN/kYjDf41Ggn+/dm1/v7y5/7+5s7+/uPJ/kYjDf49Hwv+SiUN/kolDf4wGAj+ORwJ/k4nDv5KJQ3+PR8L/k4nDv49Hwv+PR8L/jAYCP45HAn+SiUN/k4nDv4wGAj+LBYH/jkcCf5KJQ3+NRoJ/iwWB/5KJQ3+QiEM/lMpD/5TKQ/+PR8L/jUaCf4AAAAAAAAAAAAAAAAAAAAARiMN/kYjDf4wGAj+NRoJ/kIhDP41Ggn+MBgI/kYjDf5OJw7+QiEM/kIhDP49Hwv+NRoJ/jkcCf5CIQz+ORwJ/jkcCf4wGAj+TicO/iwWB/49Hwv+RiMN/jUaCf5XLBD+MBgI/lMpD/795Mn+/vDi/k4nDv45HAn+/uPJ/v3ev/41Ggn+UykP/v7mzv7+6dP+UykP/jAYCP5TKQ/+RiMN/kolDf5CIQz+TicO/k4nDv45HAn+ORwJ/iwWB/5KJQ3+SiUN/jUaCf5CIQz+SiUN/jUaCf5KJQ3+UykP/jAYCP5OJw7+NRoJ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9Hwv+RiMN/kolDf45HAn+RiMN/iwWB/5XLBD+VywQ/kYjDf4sFgf+SiUN/iwWB/5CIQz+SiUN/kolDf4wGAj+NRoJ/lcsEP5XLBD+ORwJ/kIhDP7+7t3+/eHE/v3Ztf7////+ELIb/v3cuv7+5s7+DZYX/v////794cT+/vPn/v3ev/41Ggn+UykP/kolDf5KJQ3+UykP/iwWB/5CIQz+ORwJ/kolDf5XLBD+TicO/lcsEP41Ggn+LBYH/jUaCf5GIw3+PR8L/kolDf5KJQ3+SiUN/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIhDP41Ggn+SiUN/iwWB/5TKQ/+QiEM/k4nDv45HAn+MBgI/lMpD/49Hwv+RiMN/jUaCf4wGAj+UykP/kIhDP5XLBD+QiEM/k4nDv7+8OL+/vbs/v7mzv7+6NP+/eHE/v7y5/793Lr+/ujT/v7jyf793Lr+/vDi/v3kyf794cT+/unT/lMpD/5GIw3+MBgI/jUaCf49Hwv+MBgI/kIhDP41Ggn+QiEM/lMpD/41Ggn+QiEM/jAYCP5CIQz+NRoJ/kIhDP5GIw3+ORwJ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALBYH/jAYCP5KJQ3+QiEM/lMpD/5OJw7+UykP/kolDf5TKQ/+MBgI/lMpD/5CIQz+VywQ/lMpD/4wGAj+LBYH/jkcCf795Mn+SiUN/lMpD/45HAn+NRoJ/v3ev/45HAn+SiUN/kYjDf5TKQ/+/ujT/jkcCf45HAn+ORwJ/kYjDf7+6dP+PR8L/k4nDv5OJw7+RiMN/lcsEP5TKQ/+VywQ/kolDf41Ggn+VywQ/kIhDP5KJQ3+QiEM/lMpD/5OJw7+RiMN/gAAAAA9Hwv+LBYH/jUaCf5TKQ/+AAAAAEolDf5XLBD+VywQ/k4nDv4AAAAAPR8L/jkcCf5CIQz+MBgI/gAAAABTKQ/+VywQ/k4nDv5GIw3+MBgI/jkcCf4wGAj+MBgI/kIhDP45HAn+QiEM/lcsEP5XLBD+TicO/jUaCf7+5s7+/eTJ/j0fC/4sFgf+TicO/kYjDf4sFgf+MBgI/v////7////+NRoJ/jUaCf5CIQz+LBYH/j0fC/41Ggn+/d6//v7s2P5GIw3+UykP/lMpD/5GIw3+TicO/kIhDP5TKQ/+ORwJ/kIhDP45HAn+NRoJ/jUaCf49Hwv+PR8L/gAAAAAAAAAATicO/kolDf45HAn+UykP/lMpD/5OJw7+AAAAAAAAAAA9Hwv+VywQ/lcsEP5TKQ/+SiUN/iwWB/4AAAAAAAAAAEolDf45HAn+UykP/jkcCf5KJQ3+SiUN/jkcCf5XLBD+VywQ/jAYCP5GIw3+/vDi/v7s2P7+8OL+/dy6/v3ev/4sFgf+PR8L/lMpD/5GIw3+NRoJ/jAYCP4sFgf+ORwJ/jAYCP41Ggn+RiMN/jUaCf5TKQ/+TicO/v7p0/7+9uz+/eHE/v7u3f7+9uz+/vPn/v7mzv5OJw7+SiUN/j0fC/5KJQ3+/d6//v7z5/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABKJQ3+RiMN/k4nDv5GIw3+MBgI/kYjDf5KJQ3+LBYH/jUaCf5TKQ/+NRoJ/iwWB/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4nDv41Ggn+QiEM/jUaCf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJYj/+hWA9/pBnQv6CXTv+IxIJ/iMSCf4jEgn+IxIJ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp9Hp/v////5dLBT+/////vr6+v5MJBH+/////q/W7P74+Pn++Pj5/vj4+f74+Pn++Pj5/vj4+f74+Pn++Pj5/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuNrt/pvL5v6by+b+r9bs/v7jyf7+7d3+/eHE/v3ev/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgl07/n5aOv6JYj/+gl07/iMSCf4jEgn+IxIJ/iMSCf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKvU6/7////+VSgT/v3hxP793Lr+VSgT/v////6by+b++Pj5/vj4+f74+Pn++Pj5/vj4+f74+Pn++Pj5/vj4+f4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJvL5v6v1uz+o8/o/qfR6f7+5s7+/d6//v7jyf7+8uf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJBnQv6XbEX+e1g4/pNqQ/4jEgn+IxIJ/iMSCf4jEgn+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACn0en+/////kgiEP7+7Nj+/ubO/mUwFv74+Pn+vNzu/vj4+f74+Pn++Pj5/vj4+f74+Pn++Pj5/vj4+f74+Pn+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACv1uz+r9bs/pvL5v6by+b+/uzY/v7t3f7+8uf+/uzY/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMZUD+l2xF/pBnQv6MZUD+IxIJ/iMSCf4jEgn+IxIJ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAq9Tr/vz8/f5hLhT+/uzY/v7jyf5MJBH+/////q/W7P74+Pn++Pj5/vj4+f74+Pn++Pj5/vj4+f74+Pn++Pj5/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtNjs/qvU6/6v1uz+vNzu/v7s2P7+48n+/ujT/v3hxP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+Wjr+dFM1/oliP/57WDj+gl07/nRTNf7u01D+d1U3/pBnQv57WDj+iWI//oxlQP6JYj/+7tNQ/oxlQP6TakP+/////q/W7P7////+q9Tr/v////6r1Ov+SCIQ/v3cuv7+7d3+XSwU/pvL5v7////+wN7v/vz8/f602Oz+/////v////683O7+bjQY/v////7////+TCQR/rTY7P7////+/////q/W7P7////+r9bs/v////6jz+j+/////qPP6P7////+vNzu/v////6XyeX+/////pvL5v7////+vNzu/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMxoP/uyOOP4zGg/+MxoP/jMaD/7umUv+MxoP/uyJL/6JYj/+gl07/oJdO/53VTf+MxoP/uuEJv4zGg/+MxoP/v////683O7++Pj5/qfR6f78/P3+l8nl/k0mE/7+48n+/uPJ/lksFv6jz+j+/////qvU6/7////+n83n/vz8/f7////+r9bs/moyF/7////++vr6/kgiEP6jz+j+/////v////6r1Ov+/////pvL5v7////+uNrt/v////6fzef+/////qPP6P78/P3+vNzu/v////6v1uz+/Pz9/pvL5v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH5aOv6XbEX+d1U3/pBnQv6TakP+iWI//pNqQ/7siS/+gl07/n5aOv6MZUD+jGVA/oVgPf53VTf+jGVA/pNqQ/7////+l8nl/v////6by+b+/////qfR6f5EIA/+/eHE/v7s2P5qMhf+wN7v/v////642u3+/////pvL5v76+vr+/////rja7f5uNBj+/////v////5hLhT+p9Hp/vz8/f7////+r9bs/v////642u3+/////qvU6/78/P3+q9Tr/v////602Oz+/////q/W7P7////+uNrt/v////6by+b+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACXbEX+iWI//pBnQv6MZUD+flo6/oliP/6JYj/+iWI//pNqQ/6QZ0L+jGVA/oJdO/6FYD3+k2pD/n5aOv6XbEX+/////rja7f76+vr+n83n/v////6fzef+VSgT/v////7////+ZTAW/rTY7P7////+vNzu/v////602Oz++vr6/vz8/f6v1uz+TCQR/mUwFv5VKBP+WSoT/sDe7/7////+/////sDe7/7////+p9Hp/v////602Oz+/////rTY7P7////+uNrt/v////683O7+/////sDe7/7////+uNrt/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkGdC/pdsRf6JYj/+gl07/ndVN/6FYD3+jGVA/ntYOP6CXTv+d1U3/ndVN/6QZ0L+hWA9/nRTNf6QZ0L+gl07/v////602Oz+/////rja7f7////+p9Hp/u7TUP7////+/////u7TUP6fzef+/////p/N5/7////+tNjs/v////7////+n83n/v////5ZKhP+bjQY/v////683O7+/////v////602Oz+/////rzc7v7////+l8nl/v////6XyeX+/////p/N5/7////+tNjs/v////6v1uz+/////qfR6f4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJBnQv6CXTv+hWA9/ndVN/53VTf+gl07/n5aOv5+Wjr+d1U3/oxlQP6JYj/+kGdC/pdsRf6JYj/+e1g4/oJdO/76+vr+q9Tr/v////602Oz+/////rzc7v5RJhL+/////v////5VKBP+o8/o/vr6+v6by+b+/////qfR6f7////+/////q/W7P5hLhT+/////v////5RJhL+p9Hp/v////7////+p9Hp/v////6r1Ov+/////pvL5v7////+r9bs/v////6by+b+/////qfR6f7////+q9Tr/v////7A3u/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFYD3+k2pD/oJdO/6JYj/+e1g4/ndVN/50UzX+jGVA/oliP/6QZ0L+kGdC/pdsRf6FYD3+iWI//pBnQv6MZUD++vr6/rzc7v7////+l8nl/v////602Oz+SCIQ/v////7////+YS4U/qvU6/7////+n83n/v////642u3+/////v////6by+b+TCQR/v////78/P3+USYS/sDe7/7////+/////pvL5v7////+wN7v/v////6v1uz+/////sDe7/7////+q9Tr/v////6by+b+/////qfR6f78/P3+tNjs/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd1U3/oxlQP6MZUD+dFM1/ndVN/6JYj/+l2xF/n5aOv6FYD3+gl07/ntYOP6QZ0L+jGVA/oJdO/6CXTv+dFM1/v////6r1Ov+/////rja7f78/P3+tNjs/kwkEf7////+/Pz9/kQgD/6n0en+/////qvU6/7////+p9Hp/v////7////+n83n/kwkEf7////+/////mEuFP6fzef+/////v3cuv7+8OL+/dy6/v3ev/7+8OL+/uPJ/v7o0/7+7Nj+/u3d/v7mzv793Lr+/uzY/v3ev/793r/+/vLn/v7o0/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEckE/4zGg/+LxgN/ksmFP4/IBL+SyYU/kMiE/5LJhT+JxML/isWDP4zGg/+KxYM/j8gEv47HhH+LxgN/jccEP7////+m8vm/v////6fzef+/////p/N5/5lMBb+/////v////5ZKhP+p9Hp/vj4+f6by+b+/Pz9/q/W7P76+vr++Pj5/pvL5v5MJBH+/////v////5dLBT+n83n/v////7+48n+/eHE/v3Ztf7+7Nj+/uPJ/v3cuv7+48n+/ubO/v7y5/7+7d3+/dy6/v7jyf7+48n+/ubO/v7w4v7+6NP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/IBL+PyAS/jMaD/5DIhP+RyQT/i8YDf5HJBP+IxIJ/jMaD/4rFgz+JxML/kckE/4vGA3+RyQT/isWDP5HJBP+/////rzc7v7////+uNrt/vz8/f6by+b+WSoT/vr6+v76+vr+ajIX/qPP6P7////+vNzu/v////6v1uz+/////v////7A3u/+ajIX/v////7////+ZTAW/qfR6f78/P3+/vLn/v3cuv7+6NP+/d6//v7s2P7+8uf+/d6//v7t3f7+6NP+/vLn/v7mzv7+6NP+/dm1/v7s2P7+7Nj+/eHE/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIxIJ/gAAAP4AAAD+Ox4R/j8gEv43HBD+SyYU/kMiE/4nEwv+RyQT/icTC/4vGA3+LxgN/kMiE/4zGg/+QyIT/v////602Oz++vr6/rTY7P7////+tNjs/kgiEP7////+/////kwkEf683O7+/////rja7f7////+tNjs/vr6+v7////+p9Hp/m40GP78/P3+/////lkqE/6v1uz+/////v7jyf7+8uf+/ubO/v7jyf7+48n+/ubO/v7y5/7+8OL+/dy6/v7y5/794cT+/dm1/v7w4v7+8OL+/uzY/v3cuv4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsWDP43HBD+QyIT/i8YDf4jEgn+LxgN/jseEf4vGA3+MxoP/ksmFP4zGg/+NxwQ/icTC/4rFgz+KxYM/jseEf7////+n83n/v////6fzef+/////rTY7P5ZKhP+/////v////5RJhL+wN7v/v////6jz+j++Pj5/qPP6P78/P3+/////rzc7v5lMBb+/////v////5RJhL+wN7v/v////794cT+/uzY/v3cuv7+7Nj+/ubO/v3ev/7+48n+/vLn/v7t3f7+48n+/eHE/v3ev/793Lr+/uzY/v7y5/7+48n+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMaD/7rgSH+MxoP/jMaD/4zGg/+7plL/jMaD/7rgSH+AAAAAAAAAAAAAAAAAAAAADMaD/7umUv+MxoP/jMaD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMxoP/gAAAAAAAAAAAAAAAAAAAAAAAAAA64Eh/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEckE/5bLhr+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTKhj+YzIc/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADu01D+AAAAAAAAAADu01D+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEMiE/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////7////+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEgn+IxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtLSc/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB3VTf+jGVA/pdsRf6MZUD+IxIJ/iMSCf4jEgn+IxIJ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwN7v/rzc7v642u3+wN7v/v7s2P793Lr+/u3d/v7s2P4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkGdC/oJdO/6TakP+l2xF/iMSCf4jEgn+IxIJ/iMSCf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALTY7P7A3u/+o8/o/sDe7/793r/+/ubO/v7jyf7+8uf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH5aOv57WDj+e1g4/oVgPf4jEgn+IxIJ/iMSCf4jEgn+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC42u3+tNjs/rzc7v6jz+j+/uzY/v7mzv7+6NP+/vDi/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACXbEX+l2xF/pNqQ/53VTf+IxIJ/iMSCf4jEgn+IxIJ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtNjs/q/W7P6fzef+p9Hp/v7o0/794cT+/u3d/v3ev/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFYD3+jGVA/nRTNf6MZUD+k2pD/u7TUP6FYD3+k2pD/pNqQ/6TakP+d1U3/ndVN/57WDj+kGdC/u7TUP6QZ0L+/////p/N5/7////+p9Hp/qfR6f7////+tNjs/v////6n0en+/////rja7f7////+vNzu/v////6by+b+/Pz9/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA64Eh/jMaD/7tkT3+MxoP/jMaD/4zGg/+7pZG/jMaD/4zGg/+MxoP/uyMNP4zGg/+k2pD/oVgPf5+Wjr+d1U3/uyMNP4zGg/+7plL/jMaD/4zGg/+MxoP/uuEJv4zGg/+MxoP/jMaD/7shir+MxoP/v////6v1uz+/////qfR6f6n0en+/////qPP6P7////+wN7v/v////6fzef+/////sDe7/7////+p9Hp/v////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO2RPf4AAAAAAAAAAAAAAAAAAAAAAAAAADMaD/4AAAAAAAAAAAAAAAAAAAAAAAAAAIVgPf6XbEX+k2pD/oJdO/7um1D+jGVA/oxlQP53VTf+jGVA/oxlQP6TakP+hWA9/ndVN/6JYj/+flo6/ndVN/7////+o8/o/v////683O7+uNrt/v////6n0en+/////pvL5v7////+wN7v/v////6by+b+/////qPP6P7////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFsuGv5XLBn+AAAAAAAAAAAAAAAAAAAAAAAAAAB+Wjr+e1g4/pBnQv57WDj+k2pD/n5aOv57WDj+l2xF/oliP/53VTf+kGdC/pBnQv6FYD3+flo6/oJdO/5+Wjr+/////pvL5v7////+n83n/qfR6f7////+uNrt/v////683O7+/////rTY7P7////+n83n/v////642u3+/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTKhj+UyoY/gAAAAAAAAAAAAAAAAAAAAAAAAAAd1U3/oJdO/5+Wjr+d1U3/oVgPf53VTf+jGVA/oxlQP6JYj/+hWA9/pdsRf6JYj/+iWI//n5aOv53VTf+jGVA/v////6v1uz+/////p/N5/602Oz+/////qfR6f78/P3+o8/o/v////6v1uz+/////rzc7v7////+r9bs/v////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUyoY/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIJdO/53VTf+gl07/nRTNf6MZUD+jGVA/nRTNf6CXTv+gl07/n5aOv5+Wjr+k2pD/ntYOP6MZUD+kGdC/oJdO/7////+uNrt/v////6n0en+m8vm/v////602Oz+/////rzc7v7////+m8vm/v////6r1Ov+/////rTY7P78/P3+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB3VTf+k2pD/oxlQP6JYj/+k2pD/oJdO/50UzX+d1U3/pBnQv6JYj/+gl07/oxlQP6CXTv+k2pD/oxlQP57WDj+/////pfJ5f7////+r9bs/qfR6f7////+r9bs/v////683O7+/////q/W7P78/P3+n83n/v////6n0en+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkGdC/oxlQP53VTf+k2pD/pdsRf53VTf+e1g4/ndVN/6FYD3+hWA9/oliP/57WDj+jGVA/oVgPf6FYD3+k2pD/v7y5/7+7d3+/uzY/v7jyf793r/+/vDi/v7jyf7+8uf+/dy6/v7t3f7+8OL+/eHE/v7jyf7+5s7+/u3d/v7mzv4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+IxIJ/iMSCf4jEgn+IxIJ/isWDP5LJhT+PyAS/ksmFP4zGg/+JxML/kMiE/5LJhT+PyAS/ksmFP4jEgn+IxIJ/jseEf43HBD+RyQT/jMaD/793Lr+/ujT/v7t3f7+8OL+/ubO/v3ev/7+7d3+/uPJ/v3cuv794cT+/dy6/v7jyf7+48n+/dm1/v3hxP7+6NP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtLSc/gAAAAAAAAAAAAAAAAAAAAArFgz+Ox4R/i8YDf47HhH+NxwQ/ksmFP4nEwv+Ox4R/isWDP4nEwv+PyAS/jMaD/4vGA3+IxIJ/icTC/5DIhP+/u3d/v7o0/7+8uf+/dy6/v7jyf7+7d3+/eHE/v7t3f7+5s7+/ubO/v7s2P7+48n+/vLn/v7t3f7+6NP+/uzY/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASyYU/j8gEv4nEwv+QyIT/i8YDf43HBD+MxoP/jccEP4vGA3+AAAA/gAAAP4/IBL+JxML/jMaD/4vGA3+Ox4R/v7w4v793Lr+/vDi/v3hxP7+8uf+/uzY/v7y5/7+8uf+/ubO/v3ev/7+8uf+/ubO/v7t3f7+48n+/u3d/v7s2P4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsWDP4nEwv+QyIT/kckE/4zGg/+LxgN/ksmFP4zGg/+NxwQ/kMiE/4rFgz+Ox4R/icTC/5DIhP+JxML/jMaD/7+7Nj+/ujT/v3cuv7+8uf+/u3d/v3ev/7+8OL+/vDi/v7s2P7+5s7+/vLn/v7jyf7+7Nj+/dy6/v7o0/7+48n+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==');
    }

}